# Generated by Django 4.2 on 2026-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_user_is_client_user_is_company_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
