# Generated by Django 4.2 on 2026-01-07 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_apiclient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
