# Generated by Django 4.2 on 2026-01-07 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_apiclient_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagepackage',
            options={'verbose_name': 'Message Package', 'verbose_name_plural': 'Message Packages'},
        ),
        migrations.RemoveField(
            model_name='messagepackage',
            name='whatsapp_cost_per_message',
        ),
        migrations.AddField(
            model_name='messagepackage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='messagepackage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='messagepackage',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Validity (Days)'),
        ),
        migrations.AddField(
            model_name='messagepackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='messagepackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Package'),
        ),
        migrations.AlterField(
            model_name='messagepackage',
            name='message_count',
            field=models.PositiveIntegerField(verbose_name='Number of Messages'),
        ),
        migrations.AlterField(
            model_name='messagepackage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Package Name'),
        ),
        migrations.AlterField(
            model_name='messagepackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (USD)'),
        ),
    ]
