# Generated by Django 4.2 on 2026-01-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_messagepackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepackage',
            name='plan_code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Plan Code'),
            preserve_default=False,
        ),
    ]
