# Generated by Django 4.2 on 2026-01-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_messagepackage_plan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepackage',
            name='plan_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plan Code'),
        ),
    ]
