# Generated by Django 4.2 on 2026-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_merchant_merchantinvoice_paymentlink_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('transaction_fee_percent', models.DecimalField(decimal_places=2, help_text='Platform fee percentage', max_digits=4)),
                ('max_payment_links', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
