# Generated by Django 4.2 on 2026-01-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_merchantsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marchent',
            field=models.BooleanField(default=False),
        ),
    ]
