# Generated by Django 4.2 on 2026-01-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_paymentlink_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
