# Generated by Django 4.2 on 2026-01-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_transaction_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='merchant/documents/license/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='business_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='merchant/documents/id/'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchant',
            name='onboarding_step',
            field=models.CharField(choices=[('basic_info', 'Basic Information'), ('verification', 'Verification'), ('bank_details', 'Bank Details'), ('subscription', 'Subscription Plan'), ('completed', 'Completed')], default='basic_info', max_length=50),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
